services:
  backend:
    volumes:
      - ./uploads:/uploads
      - ./thumbnails:/thumbnails
      - ./models:/models

  worker:
    volumes:
      - ./uploads:/uploads
      - ./thumbnails:/thumbnails
      - ./models:/models
